/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fms;

/**
 *
 * @author Admin
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setSize(1200,800);
        setLocation(400,150);
        setResizable(false);
        setTitle("Menu page");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fee = new javax.swing.JButton();
        stu = new javax.swing.JButton();
        lout = new javax.swing.JButton();
        pay2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Fee.setText("Fee Structure");
        Fee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeeActionPerformed(evt);
            }
        });
        getContentPane().add(Fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 285, 280, 83));

        stu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        stu.setText("Student");
        stu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuActionPerformed(evt);
            }
        });
        getContentPane().add(stu, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 134, 280, 83));

        lout.setIcon(new javax.swing.ImageIcon("E:\\Projects\\FMS\\src\\dbms fms\\Logout-icon.png")); // NOI18N
        lout.setText("Logout ");
        lout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loutActionPerformed(evt);
            }
        });
        getContentPane().add(lout, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 671, 150, 50));

        pay2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pay2.setText("Payment");
        pay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay2ActionPerformed(evt);
            }
        });
        getContentPane().add(pay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 437, 280, 83));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Projects\\FMS\\src\\dbms fms\\ak.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
            this.dispose();
            student_frame stud = new student_frame();
            stud.setVisible(true);
            stud.show();

    }//GEN-LAST:event_stuActionPerformed

    private void FeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeeActionPerformed
    this.setVisible(false);
            this.dispose();
            fee_stru_v1 sub = new fee_stru_v1();
            sub.setVisible(true);
            sub.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_FeeActionPerformed

    private void loutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loutActionPerformed
        // TODO add your handling code here:
        this.dispose();
            login re = new login();
            re.setVisible(true);
            re.show();
    }//GEN-LAST:event_loutActionPerformed

    private void pay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
            payment_v1 re = new payment_v1();
            re.setVisible(true);
            re.show();
    }//GEN-LAST:event_pay2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lout;
    private javax.swing.JButton pay2;
    private javax.swing.JButton stu;
    // End of variables declaration//GEN-END:variables
}
