package fms;

import com.toedter.calendar.JTextFieldDateEditor;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import com.toedter.calendar.JTextFieldDateEditor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class payment_v1 extends javax.swing.JFrame {

    
    conn c;
    PreparedStatement ps, psn;
    boolean found = false;
    ResultSet result;
             JTextFieldDateEditor dtedior;
    /**
     * Creates new form payment_v1
     */
    public payment_v1() {
        initComponents();
        
        
        setSize(1200,800);
        setLocation(400,150);
        setResizable(false);
        setTitle("Payment page");
        
        
        
        initdateeditor();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
private void initdateeditor(){
        dtedior =(JTextFieldDateEditor) pay_date_frm.getDateEditor();
        dtedior.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        pay_rn_frm = new javax.swing.JTextField();
        pay_Str_id_frm = new javax.swing.JTextField();
        pay_amnt_frm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        totalfeeamount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        balfee = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        g_pay_id = new javax.swing.JTextField();
        tot_fees = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        add_butn = new javax.swing.JButton();
        clr_butn = new javax.swing.JButton();
        fee = new javax.swing.JLabel();
        pidlbl = new javax.swing.JLabel();
        enno = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pay_date_frm = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        paylbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel7.setText("Payment Date :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 450, 320, 40));

        pay_rn_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_rn_frmActionPerformed(evt);
            }
        });
        pay_rn_frm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pay_rn_frmKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pay_rn_frmKeyReleased(evt);
            }
        });
        getContentPane().add(pay_rn_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 222, 300, 40));

        pay_Str_id_frm.setEditable(false);
        pay_Str_id_frm.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                pay_Str_id_frmInputMethodTextChanged(evt);
            }
        });
        pay_Str_id_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_Str_id_frmActionPerformed(evt);
            }
        });
        pay_Str_id_frm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pay_Str_id_frmKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pay_Str_id_frmKeyTyped(evt);
            }
        });
        getContentPane().add(pay_Str_id_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 275, 300, 40));

        pay_amnt_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_amnt_frmActionPerformed(evt);
            }
        });
        pay_amnt_frm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pay_amnt_frmKeyReleased(evt);
            }
        });
        getContentPane().add(pay_amnt_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 397, 300, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setText("Total fee paid :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 508, 220, 40));

        totalfeeamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalfeeamountActionPerformed(evt);
            }
        });
        totalfeeamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalfeeamountKeyReleased(evt);
            }
        });
        getContentPane().add(totalfeeamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 517, 300, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel8.setText("Balance :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 150, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setText("Enrollment No :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 220, 320, 40));

        balfee.setEditable(false);
        balfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balfeeActionPerformed(evt);
            }
        });
        getContentPane().add(balfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 300, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setText("Total Fees :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 327, 320, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setText("Payment ID :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 161, 320, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setText("Fee paid :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 395, 320, 40));

        g_pay_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g_pay_idActionPerformed(evt);
            }
        });
        g_pay_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                g_pay_idKeyReleased(evt);
            }
        });
        getContentPane().add(g_pay_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 163, 300, 40));

        tot_fees.setEditable(false);
        tot_fees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tot_feesActionPerformed(evt);
            }
        });
        tot_fees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tot_feesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tot_feesKeyTyped(evt);
            }
        });
        getContentPane().add(tot_fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 327, 300, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setText("Structure ID  :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 275, 320, 40));

        Back.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Back.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hesoyam\\Desktop\\FMS\\build\\classes\\dbms fms\\Go-back-icon.png")); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 700, 150, 50));

        add_butn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        add_butn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hesoyam\\Desktop\\FMS\\src\\dbms fms\\Add-icon.png")); // NOI18N
        add_butn.setText("ADD");
        add_butn.setMaximumSize(new java.awt.Dimension(100, 30));
        add_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_butnActionPerformed(evt);
            }
        });
        getContentPane().add(add_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 700, 150, 50));

        clr_butn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        clr_butn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hesoyam\\Desktop\\FMS\\build\\classes\\dbms fms\\Clear-icon.png")); // NOI18N
        clr_butn.setText("CLEAR");
        clr_butn.setMaximumSize(new java.awt.Dimension(100, 30));
        clr_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clr_butnActionPerformed(evt);
            }
        });
        getContentPane().add(clr_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, 150, 50));

        fee.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        fee.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 310, 40));

        pidlbl.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        pidlbl.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pidlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 310, 40));

        enno.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        enno.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(enno, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 310, 40));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -20, -1, -1));

        pay_date_frm.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(pay_date_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 462, 300, 30));

        jPanel2.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("Fees Management System");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 0, 420, 50);

        paylbl.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        paylbl.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(paylbl);
        paylbl.setBounds(650, 390, 310, 40);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 560, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel1.setText("Payment Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 369, 51));

        pack();
    }// </editor-fold>                        

    private void pay_rn_frmActionPerformed(java.awt.event.ActionEvent evt) {                                           

    }                                          

    private void pay_rn_frmKeyReleased(java.awt.event.KeyEvent evt) {                                       
        // TODO add your handling code here:
        String pat="^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match=patt.matcher(pay_rn_frm.getText());
        if(!match.matches())
        {
            enno.setText("Please Enter Number");
        }
        else
        {
            enno.setText(null);
        }
   
   
            String subcode= pay_rn_frm.getText();

            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");

                Statement st = con.createStatement();
                String q = "SELECT * FROM student WHERE S_roll_no = " + subcode;
                ResultSet rs = st.executeQuery(q);
                
                System.out.println(rs);
              /*  sem_combo.setSelectedItem("Select Semester");
                sub_name_frm.setText("");
                sub_code_frm.setText("");
                out_of_mrks_frm.setText("");*/
                while (rs.next()) {
                    found = true;
                   // sem_combo.setSelectedItem(rs.getString("sub_sem"));
                   // sub_code_frm2.setText((rs.getString("sub_code")));
                    pay_Str_id_frm.setText(rs.getString("Str_id"));
                //    sub_code_frm.setText(rs.getString("sub_code"));
                  //  out_of_mrks_frm.setText(rs.getString("sub_out_of_marks"));
                    //JOptionPane.showMessageDialog(this, "Record found..!!", "Message", JOptionPane.INFORMATION_MESSAGE);
                }
                found = false;
            } catch (SQLException sqlex) {
                System.out.print(sqlex.toString());
                System.out.print("HEEEEEEE");
            }
     
    
             
             
            enable();
            String pay= pay_Str_id_frm.getText();

            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");

                Statement st = con.createStatement();
                String q = "SELECT * FROM fee_structure WHERE Str_id = " + pay;
                ResultSet rs = st.executeQuery(q);
                
                System.out.println(rs);
              /*  sem_combo.setSelectedItem("Select Semester");
                sub_name_frm.setText("");
                sub_code_frm.setText("");
                out_of_mrks_frm.setText("");*/
                while (rs.next()) {
                    found = true;
                   // sem_combo.setSelectedItem(rs.getString("sub_sem"));
                   // sub_code_frm2.setText((rs.getString("sub_code")));
                    tot_fees.setText(rs.getString("Fee_amnt"));
                //    sub_code_frm.setText(rs.getString("sub_code"));
                  //  out_of_mrks_frm.setText(rs.getString("sub_out_of_marks"));
                   // JOptionPane.showMessageDialog(this, "Record found..!!", "Message", JOptionPane.INFORMATION_MESSAGE);
                }
                found = false;
            } catch (SQLException sqlex) {
                System.out.print(sqlex.toString());
                System.out.print("HEEEEEEE");
            }
         try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");
                Statement st = con.createStatement();
                //String Query = "insert into payment values(?,?,?,?,?,?,?)";
               String q = "SELECT sum(P_amnt) Total_paid_amt FROM payment where S_roll_no = "+ pay_rn_frm.getText();
                System.out.println(q);
                ResultSet rs = st.executeQuery(q);
                //ps = con.prepareStatement(Query);
                totalfeeamount.setText("0");
                while (rs.next()) {
                    found = true;
                    
                   totalfeeamount.setText(rs.getString("Total_paid_amt"));
                }    
 }catch (SQLException sqlex) {
                System.out.print(sqlex.toString());
                System.out.print("HEEEEEEE");
            }

    }                                      

    private void pay_Str_id_frmActionPerformed(java.awt.event.ActionEvent evt) {                                               
    }                                              

    private void pay_Str_id_frmKeyReleased(java.awt.event.KeyEvent evt) {                                           
        // TODO add your handling code here:
     /*   String pat="^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match=patt.matcher(pay_Str_id_frm.getText());
        if(!match.matches())
        {
            stridlabel.setText("Please Enter Number");
        }
        else
        {
            stridlabel.setText(null);
        }*/
     
     
     
           

    }                                          

    private void pay_Str_id_frmKeyTyped(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:

    }                                       

    private void pay_amnt_frmKeyReleased(java.awt.event.KeyEvent evt) {                                         
        // TODO add your handling code here:
        String pat="^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match=patt.matcher(pay_amnt_frm.getText());
        if(!match.matches())
        {
            paylbl.setText("Please Enter Number");
        }
        else
        {
            paylbl.setText(null);
        }
      
       
    }                                        

    private void totalfeeamountActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void balfeeActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void g_pay_idActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void tot_feesActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void tot_feesKeyReleased(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void tot_feesKeyTyped(java.awt.event.KeyEvent evt) {                                  
        // TODO add your handling code here:
    }                                 

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {                                     
        /*   try {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Fees", "root", "root123");
            Statement stat = con.createStatement();
            String q1= "select * from fee_structure where S_roll_no=" +pay_rn_frm.getText();
            String q2="select P_amnt from payment where S_roll_no=" +pay_rn_frm.getText();
            ps = con.prepareStatement(q1);
            ps = con.prepareStatement(q2);

            int fee = Integer.parseInt(q1);
            int amnt = Integer.parseInt(q2);
            int bal=fee-amnt;
            String balasString =Integer.toString(bal);
            pay_bal_frm.setText(balasString);
            String paybal = pay_bal_frm.getText();

            String sql = "update student set P_Bal='" + paybal + "', where S_roll_no=" +pay_rn_frm.getText();
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(payment_frame.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        this.dispose();
        Menu re = new Menu();
        re.setVisible(true);
        re.show();
    }                                    

    private void add_butnActionPerformed(java.awt.event.ActionEvent evt) {                                         

        // TODO add your handling code here:
        c = new conn();

        if (!pay_rn_frm.getText().equals("") & !pay_Str_id_frm.getText().equals("")  & !pay_amnt_frm.getText().equals("")) // if the JTextField is not empty then enable the button
        {
            String totalfees= tot_fees.getText();
                 String totalfeepaid= totalfeeamount.getText(); 
                 int tot =Integer.parseInt(totalfees);
                 String nowpaid= pay_amnt_frm.getText(); 
                 int total = Integer.parseInt(totalfeepaid)+Integer.parseInt(nowpaid);
                 System.out.println(total);
                 if(tot > total)
                 {
                
            
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");
                Statement st = con.createStatement();
                String Query = "insert into payment values(?,?,?,?,?,?,?)";
              // String q = "SELECT sum(P_amnt) Total_paid_amt FROM payment where S_roll_no = "+ pay_rn_frm.getText();
              //  System.out.println(q);
            //    ResultSet rs = st.executeQuery(q);
                ps = con.prepareStatement(Query);
             /*   while (rs.next()) {
                    found = true;
                    
                   totalfeeamount.setText(rs.getString("Total_paid_amt"));
                }*/
                
               
                ps = con.prepareStatement(Query);
                ps.setString(1, g_pay_id.getText());
                ps.setString(2, pay_amnt_frm.getText());
                ps.setString(3, ((JTextField)pay_date_frm.getDateEditor().getUiComponent()).getText());
                ps.setString(4, pay_rn_frm.getText());
                ps.setString(5, pay_Str_id_frm.getText());
                ps.setString(6, totalfeeamount.getText());
                ps.setString(7, tot_fees.getText());

                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "New Payment ID Generated '" + g_pay_id.getText() + "'", "Message", JOptionPane.INFORMATION_MESSAGE);

                JOptionPane.showMessageDialog(this, "Record are Save", "Message", JOptionPane.INFORMATION_MESSAGE);
                //disable();
/*
                pay_amnt_frm.setText("");
                pay_date_frm.setCalendar(null);
                pay_rn_frm.setText("");
                pay_Str_id_frm.setText("");
*/
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.toString());
                System.out.print(e.toString());
            }
            
             try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");

                Statement st = con.createStatement();
                String q = "SELECT bal FROM pay";
                ResultSet rs = st.executeQuery(q);
                
                System.out.println(rs);
              /*  sem_combo.setSelectedItem("Select Semester");
                sub_name_frm.setText("");
                sub_code_frm.setText("");
                out_of_mrks_frm.setText("");*/
                while (rs.next()) {
                    found = true;
                   // sem_combo.setSelectedItem(rs.getString("sub_sem"));
                   // sub_code_frm2.setText((rs.getString("sub_code")));
                    balfee.setText(rs.getString("bal"));
                //    sub_code_frm.setText(rs.getString("sub_code"));
                  //  out_of_mrks_frm.setText(rs.getString("sub_out_of_marks"));
                    //JOptionPane.showMessageDialog(this, "Record found..!!", "Message", JOptionPane.INFORMATION_MESSAGE);
                }
                found = false;
            } catch (SQLException sqlex) {
                System.out.print(sqlex.toString());
                System.out.print("HEEEEEEE");
            }
                 }
                 else {
                       JOptionPane.showMessageDialog(this, "Total fees Have been paid", "Information", JOptionPane.INFORMATION_MESSAGE);

                 }

        } else {
            JOptionPane.showMessageDialog(this, "Pealse Fillup All Fields", "Error", JOptionPane.ERROR_MESSAGE);
            enable();
        }

    }                                        

    private void clr_butnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        g_pay_id.setText("");
        pay_rn_frm.setText("");
        pay_Str_id_frm.setText("");
        pay_amnt_frm.setText("");
        pay_date_frm.setCalendar(null);
         pay_amnt_frm.setText("");
         tot_fees.setText("");
         totalfeeamount.setText("");
         balfee.setText("");
    }                                        

    private void pay_Str_id_frmInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                      

        // TODO add your handling code here:
    }                                                     

    private void pay_rn_frmKeyPressed(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
        
        pay_Str_id_frm.setText("");
        tot_fees.setText("");
        
        
    }                                     

    private void pay_amnt_frmActionPerformed(java.awt.event.ActionEvent evt) {                                             
      // TODO add your handling code here:
    }                                            

    private void g_pay_idKeyReleased(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
        
        
        String pat="^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match=patt.matcher(g_pay_id.getText());
        if(!match.matches())
        {
            pidlbl.setText("Please Enter Number");
        }
        else
        {
            pidlbl.setText(null);
        }
    }                                    

    private void totalfeeamountKeyReleased(java.awt.event.KeyEvent evt) {                                           
        // TODO add your handling code here:
        
        String pat="^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match=patt.matcher(totalfeeamount.getText());
        if(!match.matches())
        {
            fee.setText("Please Enter Number");
        }
        else
        {
            fee.setText(null);
        }
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment_v1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Back;
    private javax.swing.JButton add_butn;
    private javax.swing.JTextField balfee;
    private javax.swing.JButton clr_butn;
    private javax.swing.JLabel enno;
    private javax.swing.JLabel fee;
    private javax.swing.JTextField g_pay_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField pay_Str_id_frm;
    private javax.swing.JTextField pay_amnt_frm;
    private com.toedter.calendar.JDateChooser pay_date_frm;
    private javax.swing.JTextField pay_rn_frm;
    private javax.swing.JLabel paylbl;
    private javax.swing.JLabel pidlbl;
    private javax.swing.JTextField tot_fees;
    private javax.swing.JTextField totalfeeamount;
    // End of variables declaration                   
}






/*
.
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        pay_rn_frm = new javax.swing.JTextField();
        pay_Str_id_frm = new javax.swing.JTextField();
        pay_amnt_frm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        totalfeeamount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        balfee = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        g_pay_id = new javax.swing.JTextField();
        tot_fees = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        add_butn = new javax.swing.JButton();
        clr_butn = new javax.swing.JButton();
        fee = new javax.swing.JLabel();
        pidlbl = new javax.swing.JLabel();
        paylbl = new javax.swing.JLabel();
        enno = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pay_date_frm = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel7.setText("Payment Date :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 450, 320, 40));

        pay_rn_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_rn_frmActionPerformed(evt);
            }
        });
        pay_rn_frm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pay_rn_frmKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pay_rn_frmKeyReleased(evt);
            }
        });
        getContentPane().add(pay_rn_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 222, 300, 40));

        pay_Str_id_frm.setEditable(false);
        pay_Str_id_frm.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                pay_Str_id_frmInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        pay_Str_id_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_Str_id_frmActionPerformed(evt);
            }
        });
        pay_Str_id_frm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pay_Str_id_frmKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pay_Str_id_frmKeyTyped(evt);
            }
        });
        getContentPane().add(pay_Str_id_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 275, 300, 40));

        pay_amnt_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_amnt_frmActionPerformed(evt);
            }
        });
        pay_amnt_frm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pay_amnt_frmKeyReleased(evt);
            }
        });
        getContentPane().add(pay_amnt_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 397, 300, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setText("Total fee paid :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 508, 220, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel1.setText("Payment Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 369, 51));

        totalfeeamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalfeeamountActionPerformed(evt);
            }
        });
        totalfeeamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalfeeamountKeyReleased(evt);
            }
        });
        getContentPane().add(totalfeeamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 517, 300, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel8.setText("Balance :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 150, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setText("Enrollment No :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 220, 320, 40));

        balfee.setEditable(false);
        balfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balfeeActionPerformed(evt);
            }
        });
        getContentPane().add(balfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 300, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setText("Total Fees :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 327, 320, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setText("Payment ID :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 161, 320, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setText("Fee paid :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 395, 320, 40));

        g_pay_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g_pay_idActionPerformed(evt);
            }
        });
        g_pay_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                g_pay_idKeyReleased(evt);
            }
        });
        getContentPane().add(g_pay_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 163, 300, 40));

        tot_fees.setEditable(false);
        tot_fees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tot_feesActionPerformed(evt);
            }
        });
        tot_fees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tot_feesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tot_feesKeyTyped(evt);
            }
        });
        getContentPane().add(tot_fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 327, 300, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setText("Structure ID  :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 275, 320, 40));

        Back.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 700, 150, 50));

        add_butn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        add_butn.setText("ADD");
        add_butn.setMaximumSize(new java.awt.Dimension(100, 30));
        add_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_butnActionPerformed(evt);
            }
        });
        getContentPane().add(add_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 700, 150, 50));

        clr_butn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        clr_butn.setText("CLEAR");
        clr_butn.setMaximumSize(new java.awt.Dimension(100, 30));
        clr_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clr_butnActionPerformed(evt);
            }
        });
        getContentPane().add(clr_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, 150, 50));

        fee.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        fee.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 310, 40));

        pidlbl.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        pidlbl.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pidlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 310, 40));

        paylbl.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        paylbl.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(paylbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 310, 40));

        enno.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        enno.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(enno, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 310, 40));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -20, -1, -1));

        pay_date_frm.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(pay_date_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 462, 300, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pay_rn_frmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_rn_frmActionPerformed

    }//GEN-LAST:event_pay_rn_frmActionPerformed

    private void pay_rn_frmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pay_rn_frmKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_pay_rn_frmKeyReleased

    private void pay_Str_id_frmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_Str_id_frmActionPerformed
    }//GEN-LAST:event_pay_Str_id_frmActionPerformed

    private void pay_Str_id_frmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pay_Str_id_frmKeyReleased
    
    }//GEN-LAST:event_pay_Str_id_frmKeyReleased

    private void pay_Str_id_frmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pay_Str_id_frmKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_pay_Str_id_frmKeyTyped

    private void pay_amnt_frmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pay_amnt_frmKeyReleased
    
    }//GEN-LAST:event_pay_amnt_frmKeyReleased

    private void totalfeeamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalfeeamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalfeeamountActionPerformed

    private void balfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balfeeActionPerformed

    private void g_pay_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g_pay_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g_pay_idActionPerformed

    private void tot_feesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tot_feesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tot_feesActionPerformed

    private void tot_feesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tot_feesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tot_feesKeyReleased

    private void tot_feesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tot_feesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tot_feesKeyTyped

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
  
        }*/
 /*      this.dispose();
        Menu re = new Menu();
        re.setVisible(true);
        re.show();
    }//GEN-LAST:event_BackActionPerformed

    private void add_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_butnActionPerformed

       
            

        } else {
            JOptionPane.showMessageDialog(this, "Pealse Fillup All Fields", "Error", JOptionPane.ERROR_MESSAGE);
            enable();
        }
    }//GEN-LAST:event_add_butnActionPerformed

    private void clr_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clr_butnActionPerformed
        
    }//GEN-LAST:event_clr_butnActionPerformed

    private void pay_Str_id_frmInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_pay_Str_id_frmInputMethodTextChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_pay_Str_id_frmInputMethodTextChanged

    private void pay_rn_frmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pay_rn_frmKeyPressed
           
        
    }//GEN-LAST:event_pay_rn_frmKeyPressed

    private void pay_amnt_frmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_amnt_frmActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_pay_amnt_frmActionPerformed

    private void g_pay_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_g_pay_idKeyReleased
        // TODO add your handling code here:
        
        
        String pat="^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match=patt.matcher(g_pay_id.getText());
        if(!match.matches())
        {
            pidlbl.setText("Please Enter Number");
        }
        else
        {
            pidlbl.setText(null);
        }
    }//GEN-LAST:event_g_pay_idKeyReleased

    private void totalfeeamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalfeeamountKeyReleased
        // TODO add your handling code here:
        
        String pat="^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match=patt.matcher(totalfeeamount.getText());
        if(!match.matches())
        {
            fee.setText("Please Enter Number");
        }
        else
        {
            fee.setText(null);
        }
    }//GEN-LAST:event_totalfeeamountKeyReleased

    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        
    
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton add_butn;
    private javax.swing.JTextField balfee;
    private javax.swing.JButton clr_butn;
    private javax.swing.JLabel enno;
    private javax.swing.JLabel fee;
    private javax.swing.JTextField g_pay_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pay_Str_id_frm;
    private javax.swing.JTextField pay_amnt_frm;
    private com.toedter.calendar.JDateChooser pay_date_frm;
    private javax.swing.JTextField pay_rn_frm;
    private javax.swing.JLabel paylbl;
    private javax.swing.JLabel pidlbl;
    private javax.swing.JTextField tot_fees;
    private javax.swing.JTextField totalfeeamount;
    // End of variables declaration//GEN-END:variables



*/


