/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fms;

/**
 *
 * @author Admin
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


public class student_frame extends javax.swing.JFrame {

    /**
     * Creates new form student_frame
     */
     conn c;
    PreparedStatement ps, psn;
    boolean found = false;
    ResultSet result;
    
    public student_frame() {
        initComponents();
        setSize(1200,850);
        setLocation(400,150);
        setResizable(false);
        setTitle("Student Information");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
          try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");
            //String classsearch = s_cat_frm.getSelectedItem().toString();
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery("select Category from fee_structure");
            Vector v = new Vector();
            v.add("Select Category ");
            while (r != null && r.next()) {
                v.add(r.getString("Category"));
            }
         s_cat_frm.setModel(new javax.swing.DefaultComboBoxModel(v));
        } catch (SQLException ex) {
            Logger.getLogger(student_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        s_rn_frm = new javax.swing.JTextField();
        s_name_frm = new javax.swing.JTextField();
        add_butn = new javax.swing.JButton();
        clr_butn = new javax.swing.JButton();
        dlt_butn = new javax.swing.JButton();
        dsplay_butn = new javax.swing.JButton();
        mod_butn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        s_cntct_no_frm = new javax.swing.JTextField();
        classlabel = new javax.swing.JLabel();
        phnolabel = new javax.swing.JLabel();
        catlabel = new javax.swing.JLabel();
        struidlabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        deptlabel = new javax.swing.JLabel();
        strnlabel = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        s_class_frm = new javax.swing.JComboBox<>();
        s_dept_frm = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        s_cat_frm = new javax.swing.JComboBox<>();
        stru_id_frm = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Student Information");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 470, 51));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setText("Enrollment No :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 210, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setText("Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 200, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setText("Category :");
        jLabel6.setMaximumSize(new java.awt.Dimension(77, 21));
        jLabel6.setMinimumSize(new java.awt.Dimension(77, 21));
        jLabel6.setPreferredSize(new java.awt.Dimension(77, 21));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 200, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel7.setText("Structure ID :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 200, 40));

        s_rn_frm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                s_rn_frmKeyReleased(evt);
            }
        });
        getContentPane().add(s_rn_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 300, 40));

        s_name_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_name_frmActionPerformed(evt);
            }
        });
        s_name_frm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                s_name_frmKeyReleased(evt);
            }
        });
        getContentPane().add(s_name_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 300, 40));

        add_butn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        add_butn.setText("ADD");
        add_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_butnActionPerformed(evt);
            }
        });
        getContentPane().add(add_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 150, 50));

        clr_butn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        clr_butn.setText("CLEAR");
        clr_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clr_butnActionPerformed(evt);
            }
        });
        getContentPane().add(clr_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 720, 150, 50));

        dlt_butn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        dlt_butn.setText("DELETE");
        dlt_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlt_butnActionPerformed(evt);
            }
        });
        getContentPane().add(dlt_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 170, 50));

        dsplay_butn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        dsplay_butn.setText("DISPLAY");
        dsplay_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsplay_butnActionPerformed(evt);
            }
        });
        getContentPane().add(dsplay_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 620, 170, 50));

        mod_butn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        mod_butn.setText("MODIFY");
        mod_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_butnActionPerformed(evt);
            }
        });
        getContentPane().add(mod_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 150, 50));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel8.setText("Contact No :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 200, 40));

        s_cntct_no_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_cntct_no_frmActionPerformed(evt);
            }
        });
        s_cntct_no_frm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                s_cntct_no_frmKeyReleased(evt);
            }
        });
        getContentPane().add(s_cntct_no_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 300, 40));

        classlabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        classlabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(classlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 250, 239, 29));

        phnolabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        phnolabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(phnolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 239, 29));

        catlabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        catlabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(catlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 239, 29));

        struidlabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        struidlabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(struidlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 239, 29));

        namelabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        namelabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 239, 29));

        deptlabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        deptlabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(deptlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 239, 29));

        strnlabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        strnlabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(strnlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 239, 29));

        Back.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 720, 150, 50));

        s_class_frm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class", "FE", "SE", "TE", "BE" }));
        s_class_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_class_frmActionPerformed(evt);
            }
        });
        getContentPane().add(s_class_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 300, 40));

        s_dept_frm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "IT", "CS", "EE", "E&TC", "MECH", " " }));
        getContentPane().add(s_dept_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 300, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setText("Department :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 200, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel10.setText("Class :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 200, 40));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-470, -10, -1, -1));

        s_cat_frm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "OPEN", "OBC", "SC", "NT", " " }));
        s_cat_frm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        s_cat_frm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                s_cat_frmMouseReleased(evt);
            }
        });
        s_cat_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_cat_frmActionPerformed(evt);
            }
        });
        getContentPane().add(s_cat_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 300, 40));
        getContentPane().add(stru_id_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 300, 40));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-580, -20, 6280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_butnActionPerformed

        // TODO add your handling code here:
        c = new conn();

        if (!s_rn_frm.getText().equals("") & !s_name_frm.getText().equals("") &  !stru_id_frm.getText().equals("") & !s_cntct_no_frm.getText().equals("")) // if the JTextField is not empty then enable the button
        {
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");
                String Query = "insert into student values(?,?,?,?,?,?,?)";
                ps = con.prepareStatement(Query);
                ps.setString(1, s_rn_frm.getText());
                ps.setString(2, s_name_frm.getText());
                ps.setString(3, s_class_frm.getSelectedItem().toString());
                ps.setString(4, s_dept_frm.getSelectedItem().toString());
                ps.setString(6, stru_id_frm.getText());
                ps.setString(5, s_cat_frm.getSelectedItem().toString());
                ps.setString(7, s_cntct_no_frm.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record are Save", "Message", JOptionPane.INFORMATION_MESSAGE);
                //disable();
                s_rn_frm.setText("");
                s_class_frm.setSelectedItem("Select Class");
                s_name_frm.setText("");
                s_dept_frm.setSelectedItem("Select Department");
                stru_id_frm.setText("");
                s_cat_frm.setSelectedItem("Select Structure");
                s_cntct_no_frm.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.toString());
            }
            /*try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root");
                String Queryw = "insert into login values(?,?,?)";
                ps = conn.prepareStatement(Queryw);
                ps.setString(2, s_name_frm.getText());
                ps.setString(3, "student");
                ps.setString(1, s_rn_frm.getText());
                ps.executeUpdate();
                //T2.setText("");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.toString());
            }*/
        } else {
            JOptionPane.showMessageDialog(this, "Please Fillup All Fields", "Error", JOptionPane.ERROR_MESSAGE);
            enable();
        }
    }//GEN-LAST:event_add_butnActionPerformed

    private void dsplay_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsplay_butnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Student_display stud=new Student_display();
        stud.setVisible(true);
        
    }//GEN-LAST:event_dsplay_butnActionPerformed

    private void mod_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_butnActionPerformed
        // TODO add your handling code here:
        try {
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Fees", "root", "root123");
            Statement stat = con.createStatement();
            String regnnn = s_rn_frm.getText();
            String name =  s_name_frm.getText();
            String cls = s_class_frm.getSelectedItem().toString();
            String dept = s_dept_frm.getSelectedItem().toString();
            String stru = stru_id_frm.getText();
            String cat = s_cat_frm.getSelectedItem().toString();
            String cntct = s_cntct_no_frm.getText();
            System.out.println(cat);
                        System.out.println(stru);

            String sql = "update student set S_roll_no='" + regnnn + "',S_name='" + name + "',S_class='" + cls + "',S_dept='" + dept + "',S_category='" + cat + "',Str_id='" + stru + "',S_phone_no='" + cntct + "' where S_roll_no='" + regnnn + "'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Updated");
             s_rn_frm.setText("");
                s_class_frm.setSelectedItem("Select Class");
                s_name_frm.setText("");
                s_dept_frm.setSelectedItem("Select Department");
                stru_id_frm.setText("");
                s_cat_frm.setSelectedItem("Select Structure");
                s_cntct_no_frm.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mod_butnActionPerformed

    private void dlt_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlt_butnActionPerformed
        // TODO add your handling code here:
                try {
          
            conn c1 = new conn();
            ps = c1.con.prepareStatement("delete from student where S_roll_no=?");
            ps.setString(1, s_rn_frm.getText());
            ps.executeUpdate();
                s_rn_frm.setText("");
                s_class_frm.setSelectedItem("Select Class");
                s_name_frm.setText("");
                s_dept_frm.setSelectedItem("Select Department");
                stru_id_frm.setText("");
                s_cat_frm.setSelectedItem("Select Structure");
                s_cntct_no_frm.setText("");
                JOptionPane.showMessageDialog(null, "Deleted");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_dlt_butnActionPerformed

    private void clr_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clr_butnActionPerformed
        // TODO add your handling code here:
        s_rn_frm.setText("");
                s_class_frm.setSelectedItem("Select Class");
                s_name_frm.setText("");
                s_dept_frm.setSelectedItem("Select Department");
                stru_id_frm.setText("");
                            s_cat_frm.setSelectedItem("Select Category");
          
                s_cntct_no_frm.setText("");
    }//GEN-LAST:event_clr_butnActionPerformed

    private void s_cntct_no_frmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_cntct_no_frmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_cntct_no_frmActionPerformed

    private void s_rn_frmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_s_rn_frmKeyReleased
        // TODO add your handling code here:
        String pat="^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match=patt.matcher(s_rn_frm.getText());
        if(!match.matches())
        {
            strnlabel.setText("Please Enter Number");
        }
        else
        {
            strnlabel.setText(null);
        }
    }//GEN-LAST:event_s_rn_frmKeyReleased

    private void s_name_frmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_s_name_frmKeyReleased
        // TODO add your handling code here:
        String pat="^[a-zA-Z]{0,30}[ ' ' ]{0,5}[a-zA-Z]{0,20}[' ']{0,5}[a-zA-Z]{0,30}[' ']{0,5}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match=patt.matcher(s_name_frm.getText());
        if(!match.matches())
        {
            namelabel.setText("Please Enter charachters");
        }
        else
        {
            namelabel.setText(null);
        }
    }//GEN-LAST:event_s_name_frmKeyReleased

    private void s_cntct_no_frmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_s_cntct_no_frmKeyReleased
        // TODO add your handling code here:
        String pat="^[0-9]{10}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match=patt.matcher(s_cntct_no_frm.getText());
        if(!match.matches())
        {
            phnolabel.setText("Please Enter Number");
        }
        else
        {
            phnolabel.setText(null);
        }
    }//GEN-LAST:event_s_cntct_no_frmKeyReleased

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
          this.dispose();
            Menu re = new Menu();
            re.setVisible(true);
            re.show();
    }//GEN-LAST:event_BackActionPerformed

    private void s_class_frmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_class_frmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_class_frmActionPerformed

    private void s_cat_frmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_cat_frmActionPerformed
try {
                
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");
                     Statement st = con.createStatement();
                      String subcode = s_cat_frm.getSelectedItem().toString();
                       String q = "SELECT Str_id FROM fee_structure WHERE Str_id = '" +subcode +"'";
                      ResultSet rs = st.executeQuery(q);
                while (rs.next()) {
                    found = true;
                   
                    stru_id_frm.setText(rs.getString("Str_id"));
                    stru_id_frm.setText(rs.getString("Str_id"));
                }
                
         }
                catch (SQLException ex) {
            Logger.getLogger(student_frame.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_s_cat_frmActionPerformed

    private void s_cat_frmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_cat_frmMouseReleased
try {
                
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");
                     Statement st = con.createStatement();
                      String subcode = s_cat_frm.getSelectedItem().toString();
                       String q = "SELECT Str_id FROM fee_structure WHERE Str_id = '" +subcode +"'";
                      ResultSet rs = st.executeQuery(q);
                while (rs.next()) {
                    found = true;
                   
                    stru_id_frm.setText(rs.getString("Str_id"));
                }
                
         }
                catch (SQLException ex) {
            Logger.getLogger(student_frame.class.getName()).log(Level.SEVERE, null, ex);
        }                // TODO add your handling code here:

 try {
                
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");
                     Statement st = con.createStatement();
                      String subcode = s_cat_frm.getSelectedItem().toString();
                       String q = "SELECT Str_id FROM fee_structure WHERE Category = '" +subcode +"'";
                      ResultSet rs = st.executeQuery(q);
                while (rs.next()) {
                    found = true;
                   
                    stru_id_frm.setText(rs.getString("Str_id"));
                }
                
         }
                catch (SQLException ex) {
            Logger.getLogger(student_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_s_cat_frmMouseReleased

    private void s_name_frmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_name_frmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_name_frmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton add_butn;
    private javax.swing.JLabel catlabel;
    private javax.swing.JLabel classlabel;
    private javax.swing.JButton clr_butn;
    private javax.swing.JLabel deptlabel;
    private javax.swing.JButton dlt_butn;
    private javax.swing.JButton dsplay_butn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton mod_butn;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel phnolabel;
    private javax.swing.JComboBox<String> s_cat_frm;
    private javax.swing.JComboBox<String> s_class_frm;
    private javax.swing.JTextField s_cntct_no_frm;
    private javax.swing.JComboBox<String> s_dept_frm;
    private javax.swing.JTextField s_name_frm;
    private javax.swing.JTextField s_rn_frm;
    private javax.swing.JLabel strnlabel;
    private javax.swing.JTextField stru_id_frm;
    private javax.swing.JLabel struidlabel;
    // End of variables declaration//GEN-END:variables
}


/*
package fms;
import java.sql.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
//import java.math.BigInteger;


public class student_frame extends javax.swing.JFrame {

    /**
     * Creates new form student_frame
     */
  /*   conn c;
    PreparedStatement ps, psn;
    boolean found = false;
    ResultSet result;
    
    public student_frame() {
        initComponents();
        setSize(1200,850);
        setLocation(400,150);
        setResizable(false);
        setTitle("Student Information");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
          try {
              
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");
            //String classsearch = s_cat_frm.getSelectedItem().toString();
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery("select Category from fee_structure");
            Vector v = new Vector();
            v.add("Select Category ");
            while (r != null && r.next()) {
                v.add(r.getString("Category"));
            }
         //   con.close();
         s_cat_frm.setModel(new javax.swing.DefaultComboBoxModel(v));
        } catch (SQLException ex) {
            Logger.getLogger(student_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        s_rn_frm = new javax.swing.JTextField();
        s_name_frm = new javax.swing.JTextField();
        add_butn = new javax.swing.JButton();
        clr_butn = new javax.swing.JButton();
        dlt_butn = new javax.swing.JButton();
        dsplay_butn = new javax.swing.JButton();
        mod_butn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        s_cntct_no_frm = new javax.swing.JTextField();
        classlabel = new javax.swing.JLabel();
        phnolabel = new javax.swing.JLabel();
        catlabel = new javax.swing.JLabel();
        struidlabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        deptlabel = new javax.swing.JLabel();
        strnlabel = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        s_class_frm = new javax.swing.JComboBox<>();
        s_dept_frm = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        s_cat_frm = new javax.swing.JComboBox<>();
        stru_id_frm = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Student Information");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 470, 51));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setText("Enrollment No :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 210, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setText("Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 200, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setText("Category :");
        jLabel6.setMaximumSize(new java.awt.Dimension(77, 21));
        jLabel6.setMinimumSize(new java.awt.Dimension(77, 21));
        jLabel6.setPreferredSize(new java.awt.Dimension(77, 21));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 200, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel7.setText("Structure ID :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 200, 40));

        s_rn_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_rn_frmActionPerformed(evt);
            }
        });
        s_rn_frm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                s_rn_frmKeyReleased(evt);
            }
        });
        getContentPane().add(s_rn_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 300, 40));

        s_name_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_name_frmActionPerformed(evt);
            }
        });
        s_name_frm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                s_name_frmKeyReleased(evt);
            }
        });
        getContentPane().add(s_name_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 300, 40));

        add_butn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        add_butn.setText("ADD");
        add_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_butnActionPerformed(evt);
            }
        });
        getContentPane().add(add_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 150, 50));

        clr_butn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        clr_butn.setText("CLEAR");
        clr_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clr_butnActionPerformed(evt);
            }
        });
        getContentPane().add(clr_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 720, 150, 50));

        dlt_butn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        dlt_butn.setText("DELETE");
        dlt_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlt_butnActionPerformed(evt);
            }
        });
        getContentPane().add(dlt_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 170, 50));

        dsplay_butn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        dsplay_butn.setText("DISPLAY");
        dsplay_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsplay_butnActionPerformed(evt);
            }
        });
        getContentPane().add(dsplay_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 620, 170, 50));

        mod_butn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        mod_butn.setText("MODIFY");
        mod_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_butnActionPerformed(evt);
            }
        });
        getContentPane().add(mod_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 150, 50));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel8.setText("Contact No :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 200, 40));

        s_cntct_no_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_cntct_no_frmActionPerformed(evt);
            }
        });
        s_cntct_no_frm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                s_cntct_no_frmKeyReleased(evt);
            }
        });
        getContentPane().add(s_cntct_no_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 300, 40));

        classlabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        classlabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(classlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 250, 239, 29));

        phnolabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        phnolabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(phnolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 239, 29));

        catlabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        catlabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(catlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 239, 29));

        struidlabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        struidlabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(struidlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 239, 29));

        namelabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        namelabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 239, 29));

        deptlabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        deptlabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(deptlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 239, 29));

        strnlabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        strnlabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(strnlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 239, 29));

        Back.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 720, 150, 50));

        s_class_frm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class", "FE", "SE", "TE", "BE" }));
        s_class_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_class_frmActionPerformed(evt);
            }
        });
        getContentPane().add(s_class_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 300, 40));

        s_dept_frm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "IT", "CS", "EE", "E&TC", "MECH", " " }));
        getContentPane().add(s_dept_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 300, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setText("Department :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 200, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel10.setText("Class :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 200, 40));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-470, -10, -1, -1));

        s_cat_frm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "OPEN", "OBC", "SC", "NT", " " }));
        s_cat_frm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        s_cat_frm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                s_cat_frmMouseReleased(evt);
            }
        });
        s_cat_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_cat_frmActionPerformed(evt);
            }
        });
        getContentPane().add(s_cat_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 300, 40));

        stru_id_frm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stru_id_frmActionPerformed(evt);
            }
        });
        getContentPane().add(stru_id_frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 300, 40));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-580, -20, 6280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_butnActionPerformed

        // TODO add your handling code here:
        c = new conn();

        if (!s_rn_frm.getText().equals("") & !s_name_frm.getText().equals("") &  !stru_id_frm.getText().equals("") & !s_cntct_no_frm.getText().equals("")) // if the JTextField is not empty then enable the button
        {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");
                String Query = "insert into student values(?,?,?,?,?,?,?)";
                ps = con.prepareStatement(Query);
                ps.setInt(1, Integer.parseInt(s_rn_frm.getText()));
                ps.setString(2, s_name_frm.getText());
                //System.out.println("\n After Name");
                ps.setString(3, s_class_frm.getSelectedItem().toString());
                ps.setString(4, s_dept_frm.getSelectedItem().toString());               
                ps.setInt(5,Integer.parseInt(s_cntct_no_frm.getText()));
                //System.out.println("\n After Contact");
                ps.setString(6, s_cat_frm.getSelectedItem().toString());
                ps.setInt(7,Integer.parseInt(stru_id_frm.getText()));
                
                //System.out.println("\n After Struct");
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record are Save", "Message", JOptionPane.INFORMATION_MESSAGE);
                //disable();
                s_rn_frm.setText("");
                
                s_class_frm.setSelectedItem("Select Class");
                s_name_frm.setText("");
                s_dept_frm.setSelectedItem("Select Department");
                stru_id_frm.setText("");
                s_cat_frm.setSelectedItem("Select Structure");
                s_cntct_no_frm.setText("");
              //  con.close();
            } 
            catch (HeadlessException | NumberFormatException | SQLException e) {
                e.printStackTrace();
//                JOptionPane.showMessageDialog(this, e.toString());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(student_frame.class.getName()).log(Level.SEVERE, null, ex);
            }
            /*try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root");
                String Queryw = "insert into login values(?,?,?)";
                ps = conn.prepareStatement(Queryw);
                ps.setString(2, s_name_frm.getText());
                ps.setString(3, "student");
                ps.setString(1, s_rn_frm.getText());
                ps.executeUpdate();
                //T2.setText("");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.toString());
            }*/
      /*  } else {
            JOptionPane.showMessageDialog(this, "Please Fillup All Fields", "Error", JOptionPane.ERROR_MESSAGE);
            enable();
        }
    }//GEN-LAST:event_add_butnActionPerformed

    private void dsplay_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsplay_butnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Student_display stud=new Student_display();
        stud.setVisible(true);
        
    }//GEN-LAST:event_dsplay_butnActionPerformed

    private void mod_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_butnActionPerformed
        // TODO add your handling code here:
        try {
            
            Connection con = DriverManager.getConnection("jdbc:mys Statement stat = con.createStatement();\n" +
"            String regnnn = s_rn_frm.getTextql://localhost:3306/fees", "root", "root123");
            Statement stat = con.createStatement();
            String regnnn = s_rn_frm.getText();
            //int regnnn1=Integer.parseInt(regnnn);
            String name =  s_name_frm.getText();
            String cls = s_class_frm.getSelectedItem().toString();
            String dept = s_dept_frm.getSelectedItem().toString();
            String cntct = s_cntct_no_frm.getText();
            //cntct1=Integer.parseInt(cntct);
            String cat = s_cat_frm.getSelectedItem().toString();
            String stru = stru_id_frm.getText();
            //int stru1=Integer.parseInt(stru);
            
             
            System.out.println(cat);
                        System.out.println(stru);

            String sql = "update student set S_roll_no='" + regnnn + "',S_name='" + name + "',S_class='" + cls + "',S_dept='" + dept + "',S_category='" + cat + "',Str_id='" + stru + "',S_phone_no='" + cntct + "' where S_roll_no='" + regnnn + "'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Updated");
             s_rn_frm.setText("");
                s_class_frm.setSelectedItem("Select Class");
                s_name_frm.setText("");
                s_dept_frm.setSelectedItem("Select Department");
                stru_id_frm.setText("");
               s_cat_frm.setSelectedItem("Select Structure");
                s_cntct_no_frm.setText("");
                con.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mod_butnActionPerformed

    private void dlt_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlt_butnActionPerformed
        // TODO add your handling code here:
                try {
          
            conn c1 = new conn();
            ps = c1.con.prepareStatement("delete from student where S_roll_no=?");
            ps.setString(1, s_rn_frm.getText());
            ps.executeUpdate();
                s_rn_frm.setText("");
                s_class_frm.setSelectedItem("Select Class");
                s_name_frm.setText("");
                s_dept_frm.setSelectedItem("Select Department");
                stru_id_frm.setText("");
                s_cat_frm.setSelectedItem("Select Structure");
                s_cntct_no_frm.setText("");
                JOptionPane.showMessageDialog(null, "Deleted");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_dlt_butnActionPerformed

    private void clr_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clr_butnActionPerformed
        // TODO add your handling code here:
        s_rn_frm.setText("");
                s_class_frm.setSelectedItem("Select Class");
                s_name_frm.setText("");
                s_dept_frm.setSelectedItem("Select Department");
                stru_id_frm.setText("");
                s_cat_frm.setSelectedItem("Select Category");
                s_cntct_no_frm.setText("");
    }//GEN-LAST:event_clr_butnActionPerformed

    private void s_cntct_no_frmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_cntct_no_frmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_cntct_no_frmActionPerformed

    private void s_rn_frmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_s_rn_frmKeyReleased
        // TODO add your handling code here:
        String pat="^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match=patt.matcher(s_rn_frm.getText());
        if(!match.matches())
        {
            strnlabel.setText("Please Enter Number");
        }
        else
        {
            strnlabel.setText(null);
        }
    }//GEN-LAST:event_s_rn_frmKeyReleased

    private void s_name_frmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_s_name_frmKeyReleased
        // TODO add your handling code here:
        String pat="^[a-zA-Z]{0,30}[ ' ' ]{0,5}[a-zA-Z]{0,20}[' ']{0,5}[a-zA-Z]{0,30}[' ']{0,5}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match=patt.matcher(s_name_frm.getText());
        if(!match.matches())
        {
            namelabel.setText("Please Enter charachters");
        }
        else
        {
            namelabel.setText(null);
        }
    }//GEN-LAST:event_s_name_frmKeyReleased

    private void s_cntct_no_frmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_s_cntct_no_frmKeyReleased
        // TODO add your handling code here:
        String pat="^[0-9]{10}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match=patt.matcher(s_cntct_no_frm.getText());
        if(!match.matches())
        {
            phnolabel.setText("Please Enter Number");
        }
        else
        {
            phnolabel.setText(null);
        }
    }//GEN-LAST:event_s_cntct_no_frmKeyReleased

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
          this.dispose();
            Menu re = new Menu();
            re.setVisible(true);
            re.show();
    }//GEN-LAST:event_BackActionPerformed

    private void s_class_frmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_class_frmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_class_frmActionPerformed

    private void s_cat_frmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_cat_frmActionPerformed
try {
                
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");
                     Statement st = con.createStatement();
                      String subcode = s_cat_frm.getSelectedItem().toString();
                       String q = "SELECT Str_id FROM fee_structure WHERE Str_id = '" +subcode +"'";
                      ResultSet rs = st.executeQuery(q);
                while (rs.next()) {
                    found = true;
                   
                    stru_id_frm.setText(rs.getString("Str_id"));
                    stru_id_frm.setText(rs.getString("Str_id"));
                }
              //  con.close();
         }
                catch (SQLException ex) {
           Logger.getLogger(student_frame.class.getName()).log(Level.SEVERE, null, ex);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_s_cat_frmActionPerformed

    private void s_cat_frmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_cat_frmMouseReleased
try {
                
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");
                     Statement st = con.createStatement();
                      String subcode = s_cat_frm.getSelectedItem().toString();
                       String q = "SELECT Str_id FROM fee_structure WHERE Str_id = '" +subcode +"'";
                      ResultSet rs = st.executeQuery(q);
                while (rs.next()) {
                    found = true;
                   
                    stru_id_frm.setText(rs.getString("Str_id"));
                }
               // con.close();
         }
                catch (SQLException ex) {
            Logger.getLogger(student_frame.class.getName()).log(Level.SEVERE, null, ex);
        }                // TODO add your handling code here:

 try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees", "root", "root123");
                     Statement st = con.createStatement();
                      String subcode = s_cat_frm.getSelectedItem().toString();
                       String q = "SELECT Str_id FROM fee_structure WHERE Category = '" +subcode +"'";
                      ResultSet rs = st.executeQuery(q);
                while (rs.next()) {
                    found = true;
                   
                    stru_id_frm.setText(rs.getString("Str_id"));
                }
                con.close();
         }
                catch (SQLException ex) {
           // Logger.getLogger(student_frame.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_s_cat_frmMouseReleased

    private void s_name_frmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_name_frmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_name_frmActionPerformed

    private void s_rn_frmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_rn_frmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_rn_frmActionPerformed

    private void stru_id_frmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stru_id_frmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stru_id_frmActionPerformed
*/
    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
  /*      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton add_butn;
    private javax.swing.JLabel catlabel;
    private javax.swing.JLabel classlabel;
    private javax.swing.JButton clr_butn;
    private javax.swing.JLabel deptlabel;
    private javax.swing.JButton dlt_butn;
    private javax.swing.JButton dsplay_butn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton mod_butn;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel phnolabel;
    private javax.swing.JComboBox<String> s_cat_frm;
    private javax.swing.JComboBox<String> s_class_frm;
    private javax.swing.JTextField s_cntct_no_frm;
    private javax.swing.JComboBox<String> s_dept_frm;
    private javax.swing.JTextField s_name_frm;
    private javax.swing.JTextField s_rn_frm;
    private javax.swing.JLabel strnlabel;
    private javax.swing.JTextField stru_id_frm;
    private javax.swing.JLabel struidlabel;
    // End of variables declaration//GEN-END:variables
}
*/